#---Notifcations---

notifications:
  email: false

#---Language---

language: python

#---Branches---

branches:
  only:
    - master

#---Environment---

sudo: required

#---Services---

#-----BEGIN BUILD-----

 #--Before Install--

 #--Install--

install:
  - pip install ansible

 #--Before Script--

 #--Script--

script:
  - "echo 'allow_world_readable_tmpfiles=True' >> ansible.cfg"
  - "echo 'authn_simple: true' >> vars/main.yml"
  - "echo 'authn_db: true' >> vars/main.yml"
  - "echo 'authn_ldap: true' >> vars/main.yml"
  - "echo 'authn_anon: true' >> vars/main.yml"
  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local -vvvv --sudo"
  
 #--After Script--

 #--Before Deploy--

 #--Deploy--

 #--After Deploy--
