#---Notifcations---

notifications:
  email: false

#---Language---

language: python

#---Branches---

branches:
  only:
    - master

#---Environment---

sudo: required

#---Services---

#-----BEGIN BUILD-----

 #--Before Install--

 #--Install--

install:
  - pip install ansible
  - pip install selenium

 #--Before Script--

 #--Script--

# Many warnings are ignored on the Idempotence run, this is to reduce clutter, making it easier to see which tasks are not idempotent, all default warnings are enabled for the first run

script:
  - "echo 'allow_world_readable_tmpfiles=True' >> ansible.cfg"		# Allows world readable temp files, not secure should only be used within Travis
  - "sed -i 's/authn_simple: false/authn_simple: true/g' config.yml"	# Set Authn Simple to true
  - "sed -i 's/authn_db: false/authn_db: true/g' config.yml"		# Set Authn DB to true
  - "sed -i 's/authn_ldap: false/authn_ldap: true/g' config.yml"	# Set Authn LDAP to true
  - "sed -i 's/authn_anon: false/authn_anon: true/g' config.yml"	# Set Authn Anon to true
  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local"
#
  - "sed -i 's/delete_fac: false/delete_fac: true/g' config.yml"	# Test Deletion Script
  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local --tags 'pycat'"
#
  - "sed -i 's/delete_fac: true/delete_fac: false/g' config.yml"	# Test Idempotence
  - "echo 'stdout_callback = actionable' >> ansible.cfg"		# Only Output Changed or Failed Tasks
  - "echo 'deprecation_warnings = False' >> ansible.cfg"		# Ignore Depriciation Warnings
  - "echo 'command_warnings = False' >> ansible.cfg"			# Ignore Command Module Warnings
  - "echo 'system_warnings = False' >> ansible.cfg"			# Ignore System Warnings
  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local --diff"  
# Run selenium (if 'Failed' exists in output, fail the build)
# Check files downloaded by selenium (fail if non-existent)


 #--After Script--

 #--Before Deploy--

 #--Deploy--

 #--After Deploy--
