#---Notifcations---

notifications:
  email: false

#---Language---

language: python

#---Branches---

branches:
  # Whitelist
  only:
    - master

#---Environment---

sudo: required

#---Services---

services:
  - docker

#-----BEGIN BUILD-----

 #--Before Install--

 #--Install--

install:

  - pip install ansible

 #--Before Script--

 #--Script--

script:
  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local -vvvv"

 #--After Script--

 #--Before Deploy--

 #--Deploy--

 #--After Deploy--
