#---Notifcations---

notifications:
  email: false

#---Language---

language: python
#python: "2.6"

#---Branches---

branches:
  # Whitelist
  only:
    - master

#---Environment---

sudo: required

#---Services---


#-----BEGIN BUILD-----

 #--Before Install--

 #--Install--

install:

  - pip install ansible

 #--Before Script--

 #--Script--

script:
  - "ls"
  - "ls /root/"
  - "ls /home/"
  - "sudo -i"
  - "ls /root/"
  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --syntax-check --connection=local -vvvv"
  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local -vvvv"

 #--After Script--

 #--Before Deploy--

 #--Deploy--

 #--After Deploy--
