#---Notifcations---

notifications:
  email: false

#---Language---

language: python

#---Branches---

branches:
  only:
    - master

#---Environment---

sudo: required

#---Services---

#-----BEGIN BUILD-----

 #--Before Install--

 #--Install--

install:
  - pip install ansible

 #--Before Script--

 #--Script--

script:
  - "echo 'allow_world_readable_tmpfiles=True' >> ansible.cfg"
  - "sed -i 's/authn_simple: false/authn_simple: true/g' config.yml"
  - "sed -i 's/authn_db: false/authn_db: true/g' config.yml"
  - "sed -i 's/authn_ldap: false/authn_ldap: true/g' config.yml"
  - "sed -i 's/authn_anon: false/authn_anon: true/g' config.yml"
  - "cat config.yml"
  - "ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --connection=local -vvvv --sudo"
  
 #--After Script--

 #--Before Deploy--

 #--Deploy--

 #--After Deploy--
