---
- hosts: all
  vars: #These variables are declared here because they are used by multiple roles 

   #non-root user
    user_name: user1
    user_pass: $1$ICat$5zAyObeqGFnoaH4Dz8PSY1  #encrypted with 'python -c 'import crypt; print crypt.crypt("{{password}}", "$1$ICat$")'
    download_dir: /home/{{ user_name }}/icatdownloads/

   #Mysql user
    mysql_root_pass: pw
    mysql_user: icat
    mysql_pass: icat
    mysql_db_name: icat
    mysql_cnf: |
      # MySQL
      db.target      = mysql
      db.driver      = com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      db.url         = jdbc:mysql://localhost:3306/icat
      db.username    = {{ mysql_user }}
      db.password    = {{ mysql_pass }}

   #glassfish container block
    glassfish_cnf: |
      #Glassfish
      secure    = false
      container = Glassfish
      home      = /home/{{ user_name }}/glassfish4
      port      = 4848


  roles:
    - {role: Update,      become: yes, become_user: root}
    - {role: Java,        become: yes, become_user: root}                                               
    - {role: Pexpect,     become: yes, become_user: root}
    - {role: MySQL,       become: yes, become_user: root}                                              
    - {role: CreateUser,  become: yes, become_user: root}
    - {role: Glassfish,   become: yes, become_user: "{{ user_name }}"}    
    - {role: Authn,       become: yes, become_user: "{{ user_name }}"}  
    - {role: ICAT,        become: yes, become_user: "{{ user_name }}"}  
    - {role: IDSStorage,  become: yes, become_user: "{{ user_name }}"}  
    - {role: IDS,         become: yes, become_user: "{{ user_name }}"}  
    - {role: TestData,    become: yes, become_user: "{{ user_name }}"} 
    - {role: TopCat,      become: yes, become_user: "{{ user_name }}"} 
#    - {role: RmDownloads, become: yes, become_user: "{{ user_name }}"}

#NOTES:
#Roles currently assume that all previous roles have been installed as specified by install tutorial
#these need to be updated to detect and account for any chnages in previous roles
#eg using different authenticator plugin to authnsimple
