---
# tasks file for /etc/ansible/roles/IDS
- name: Checking download directory
  file:
    path: "{{ download_dir }}"
    state: directory

- name: Downloading {{ ids_zip }}
  get_url:
    url: "{{ ids_src }}"
    dest: "{{ download_dir }}"
    
- name: Unzipping {{ ids_zip }}
  unarchive:
    src: "{{ download_dir }}{{ ids_zip }}"
    dest: "/home/{{ user_name }}/"

- name: Creating {{ ids_setup_prop }}
  file:
    path: "/home/{{ user_name }}/ids.server/{{ ids_setup_prop }}"
    state: touch 

- name: Configuring {{ ids_setup_prop }}
  blockinfile:
    path: "/home/{{ user_name }}/ids.server/{{ ids_setup_prop }}"
    block: "{{ glassfish_cnf }}"
    state: present

- name: Configuring {{ ids_setup_prop }}
  lineinfile:
    path: "/home/{{ user_name }}/ids.server/{{ ids_setup_prop }}"
    regexp: "libraries"
    line: libraries=ids.storage_file*.jar
    state: present

- name: Creating cache
  file:
    path: "/home/{{ user_name }}/{{ mysql_db_name }}/main/ids/cache/"
    state: directory

- name: Creating {{ ids_prop }}
  copy:
    src: "/home/{{ user_name }}/ids.server/{{ ids_prop }}.example"
    dest: "/home/{{ user_name }}/ids.server/{{ ids_prop }}"

- name: Configuring {{ ids_prop }}
  lineinfile:
    path: "/home/{{ user_name }}/ids.server/{{ ids_prop }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "icat.url",    line: "icat.url = http://localhost:8080" }
    - { regexp: "cache.dir",   line: "cache.dir = /home/{{ user_name }}/{{ mysql_db_name }}/main/ids/cache/" }
    - { regexp: "reader",      line: "reader = simple username root password {{ mysql_root_pass }}" }
    - { regexp: ".lastIdFile", line: "filesCheck.lastIdFile = /home/{{ user_name }}/{{ mysql_db_name }}/main/ids/lasIdFile" }
    - { regexp: ".errorlog",   line: "filesCheck.errorLog = /home/{{ user_name }}/{{ mysql_db_name }}/main/ids/errorLog" }

- name: Running setup
  shell:
    cmd: ./setup install
    chdir: "/home/{{ user_name }}/ids.server/"
