---
- name: Checking download directory
  file:
    path: "{{ download_dir }}"
    state: directory

- name: Downloading {{ authn_zip }}
  get_url:
    url: "{{ authn_src }}"
    dest: "{{ download_dir }}"

- name: Unzipping {{ authn_zip }}
  unarchive:
    src: "{{ download_dir }}{{ authn_zip }}"
    dest: "/home/{{ user_name }}"

- name: Creating {{ authn_setup_prop }}
  file:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_setup_prop }}"
    state: touch

- name: Configuring {{ authn_setup_prop }}
  blockinfile:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_setup_prop }}"
    block: |
      {{ glassfish_cnf }}

- name: Creating {{ authn_prop }}
  file:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_prop }}"
    state: touch

- name: Creating usernames and passwords in {{ authn_prop }}
  blockinfile:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_prop }}"
    block: |
      #User list
      user.list = root ingest {{ user_name }}

      user.root.password = pw
      user.ingest.password = ingest
      user.{{ user_name }}.password = {{ user_pass }}

      mechanism = simple

- name: Installing Authentication
  shell:
    cmd: ./setup install
    chdir: "/home/{{ user_name }}/authn.simple"
