---

- name: "{{ play_name }}Loading Pre-playbook Check"
  include: "preplay.yml"

#---

#---Download Glassfish---

- stat:
    path: "{{ download_dir }}{{ glassfish_zip }}"
  register: gf_zip

- name: "{{ play_name }}Downloading Glassfish"
  get_url:
    url: "{{ glassfish_src }}"
    dest: "{{ download_dir }}"
  when: gf_zip.stat.exists == false

#---

#---Unzip Glassfish---

- stat:
    path: "{{ glassfish_path }}"
  register: gf_dir

- name: "{{ play_name }}Unzipping {{ glassfish_zip }}"
  unarchive:
    src: "{{ download_dir }}{{ glassfish_zip }}"
    dest: "{{ user_home }}"
    remote_src: yes
  when:
    - gf_dir.stat.exists == false

#---

#---Download Glassfish setup script---

- stat:
    path: "{{ user_home }}/setup-glassfish.py"
  register: gf_script

- name: "{{ play_name }}Downloading Glassfish setup script"
  get_url:
    url: "{{ glassfish_setup }}"
    dest: "{{ user_home }}"
  when: gf_script.stat.exists == false

#---

#---Run Glassfish setup script---

- stat:
    path: "{{ glassfish_path }}/glassfish/domains/{{ glassfish_domain }}"
  register: gf_dom

- name: "{{ play_name }}Stopping {{ glassfish_domain }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ glassfish_path }}/bin"
  command: "nohup asadmin stop-domain {{ glassfish_domain }}"
  when: gf_dom.stat.exists == true

- name: "{{ play_name }}Running setup script"
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ user_name }}/glassfish4/bin"
  command: "python {{ user_home }}/setup-glassfish.py {{ glassfish_domain }} 75% {{ mysql_root_pass }}"

#---

#---Configuring Glassfish Domain---

- name: "{{ play_name }}Finding mysql java connector"
  find:
    paths: /usr/share/java
    patterns: 'mysql-connector-java-*.jar'
  register: sql_java

- name: "{{ play_name }}Moving Java Connector File for {{ glassfish_domain }} and MySQL"
  copy:
    src: "{{ sql_java.files[0].path }}"
    dest: "{{ glassfish_path }}/glassfish/domains/{{ glassfish_domain }}/lib/ext/"
    remote_src: yes

- name: "{{ play_name }}Restarting {{ glassfish_domain }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ glassfish_path }}/bin"
  command: "nohup {{ item }}"
  with_items:
  - "asadmin restart-domain {{ glassfish_domain }}"
  - "asadmin list-domains"
  
#---
