---

- name: "{{ play_name }}Loading Pre-playbook Check"
  include: "preplay.yml"

#---

- name: "{{ play_name }}Changing filenames for versions older than 4.9.0"
  set_fact:
    icat_setup: icat-setup.properties
    icat_prop: icat.properties
  when:
    - icat_version | version_compare('4.9.0','<') == true

#---Downloading ICAT Server---

- stat:
    path: "{{ download_dir }}{{ icat_zip }}"
  register: is_zip

- name: "{{ play_name }}Downloading {{ icat_zip }}"
  get_url:
    url: "{{ icat_src }}"
    dest: "{{ download_dir }}"
  when: is_zip.stat.exists == false

#---

#---Unzipping Icat Server---

- stat:
    path: "{{ icat_path }}"
  register: is_dir

- name: "{{ play_name }}Unzipping {{ icat_zip }}"
  unarchive:
    src: "{{ download_dir }}{{ icat_zip }}"
    dest: "{{ user_home }}/"
    remote_src: yes
  when: is_dir.stat.exists == false

#---

#---Setup file---

- stat:
    path: "{{ icat_path }}/{{ icat_setup }}"
  register: is_setup

- name: "{{ play_name }}Copying {{ icat_setup }}.example"
  copy:
    src: "{{ icat_path }}/{{ icat_setup }}.example"
    dest: "{{ icat_path }}/{{ icat_setup }}"
    remote_src: yes
  when:
    - is_setup.stat.exists == false

- name: "{{ play_name }}Configuring {{ icat_setup }}"
  lineinfile:
    path: "{{ icat_path }}/{{ icat_setup }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ icat_cnf_list }}"

#---

#---Lucene Directory---

- name: "{{ play_name }}Creating Lucene directory"
  file: 
    path: "{{ lucene_dir }}"
    state: directory

#---

#---Script Directory---

- name: "{{ play_name }}Creating script directory"
  file:
    path: "{{ user_home }}/bin"
    state: directory

- name: "{{ play_name }}Adding script directory to bashrc"
  lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: "export PATH=$PATH:{{ user_home }}/bin"

#---

#---Icat Properties---

- name: "{{ play_name }}Creating {{ icat_prop }}"
  copy:
    src: "{{ icat_path }}/{{ icat_prop }}.example"
    dest: "{{ icat_path }}/{{ icat_prop }}"
    remote_src: yes
    force: no

- name: "{{ play_name }}Configuring {{ icat_prop }}"
  lineinfile:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'rootUserNames', line: 'rootUserNames = {{ icat_mech }}/{{ icat_root }}' }
    - { regexp: 'lucene.directory', line: 'lucene.directory = {{ lucene_dir }}' }

- name: "{{ play_name }}Correcting url in {{ icat_prop }}"
  replace:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "https://localhost:8181"
    replace: "{{ icat_url }}"

#--Authn--

- set_fact:
    authn_list:

- set_fact:
    authn_list: "{{ authn_list }} simple"
  when: authn_simple == true

- set_fact:
    authn_list: "{{ authn_list }} db"
  when: authn_db == true

- set_fact:
    authn_list: "{{ authn_list }} ldap"
  when: authn_ldap == true

- set_fact:
    authn_list: "{{ authn_list }} anon"
  when: authn_anon == true

- name: "{{ play_name }}Setting Authn List to {{ authn_list }}"
  lineinfile:
    dest: "{{ icat_path }}/{{ icat_prop }}"
    regexp: authn.list
    line: "authn.list = {{ authn_list }}"

- name: "{{ play_name }}Adding Authenticator Lines to {{ icat_prop }}"
  lineinfile:
    dest: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^authn.simple.friendly"
    line: "authn.simple.friendly = Simple"
    insertafter: "authn.simple"

#--

#--Authn Simple--

- name: "{{ play_name }}Configuring {{ icat_prop }} - Uncommenting Authn Simple Lines"
  replace:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^!authn.simple"
    replace: "authn.simple"
  when: authn_simple == true

- name: "{{ play_name }}Configuring {{ icat_prop }} - Commenting Out Authn Simple Lines"
  replace:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^authn.simple"
    replace: "!authn.simple"
  when: authn_simple == false

- name: "{{ play_name }}Replacing authn.simple.url with authn.simple.jndi for versions before 2.0.0"
  lineinfile:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^authn.simple.url"
    line: "authn.simple.jndi  = java:global/authn.simple-{{ simple_version }}/SIMPLE_Authenticator"
  when:
    - authn_simple == true
    - simple_version | version_compare('2.0.0','<') == true
#--

#--Authn DB--

- name: "{{ play_name }}Configuring {{ icat_prop }} - Uncommenting Authn DB Lines"
  replace:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^!authn.db"
    replace: "authn.db"
  when: authn_db == true

- name: "{{ play_name }}Configuring {{ icat_prop }} - Commenting Out Authn DB Lines"
  replace:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^authn.db"
    replace: "!authn.db"
  when: authn_db == false

- name: "{{ play_name }}Replacing authn.db.url with authn.db.jndi"
  lineinfile:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^authn.db.url"
    line: "authn.db.jndi  = java:global/authn.db-{{ db_version }}/DB_Authenticator"
  when:
    - authn_db == true
    - db_version | version_compare('2.0.0','<') == true
# Uncomment when earliest restful version is known

#--

#--Authn LDAP--

- name: "{{ play_name }}Configuring {{ icat_prop }} - Uncommenting Authn LDAP Lines"
  replace:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^!authn.ldap"
    replace: "authn.ldap"
  when: authn_ldap == true

- name: "{{ play_name }}Configuring {{ icat_prop }} - Commenting Out Authn LDAP Lines"
  replace:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^authn.ldap"
    replace: "!authn.ldap"
  when: authn_ldap == false

- name: "{{ play_name }}Replacing authn.ldap.url with authn.ldap.jndi for versions before 2.0.0"
  lineinfile:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^authn.ldap.url"
    line: "authn.ldap.jndi  = java:global/authn.ldap-{{ ldap_version }}/LDAP_Authenticator"
  when:
    - authn_ldap == true
    - ldap_version | version_compare('2.0.0','<') == true

#--

#--Authn Anon--

- name: "{{ play_name }}Configuring {{ icat_prop }} - Uncommenting Authn Anon Lines"
  replace:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^!authn.anon"
    replace: "authn.anon"
  when: authn_anon == true

- name: "{{ play_name }}Configuring {{ icat_prop }} - Commenting Out Authn Anon Lines"
  replace:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^authn.anon"
    replace: "!authn.anon"
  when: authn_anon == false

- name: "{{ play_name }}Replacing authn.anon.url withn authn.anon.jndi for versions before 2.0.0"
  lineinfile:
    path: "{{ icat_path }}/{{ icat_prop }}"
    regexp: "^authn.anon.url"
    line: "authn.anon.jndi  = java:global/authn.anon-{{ anon_version }}/ANON_Authenticator"
  when:
    - authn_anon == true
    - anon_version | version_compare('2.0.0','<') == true
# Uncomment when earliest restful version known

#--

#---

#---Running Setup---

- name: "{{ play_name }}Installing ICAT server"
  shell:
    cmd: ./setup install
    chdir: "{{ icat_path }}"

- name: "{{ play_name }}Checking ICAT"
  command: "curl -k {{ icat_url }}/icat/version"

#---
