---

#---Downloading Packages for Yum---

- name: "{{ play_name }}Installing Java For Yum"
  yum:
    name: "{{ java_pkg_yum }}"
  when:
    - ansible_pkg_mgr == "yum"
  tags:
    - yum

#---

#---Downloading packages for apt---

- name: "{{ play_name }}Adding Java repository to Apt"
  apt_repository:
    repo: "{{ java_repo_apt }}"
    state: present
  when: 
    - ansible_pkg_mgr == "apt"
  tags:
    - apt
    
- name: "{{ play_name }}Installing {{ java_package_debian }} with Apt"
  apt:
    name: "{{ java_pkg_apt }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"
  tags:
    - apt

#---

- name: "{{ play_name }}Checking Java version"
  command: javac -version
