---
#main.yml file for ICATInstall

- include_vars: ../config.yml

- name: Gathering Variables
  include_vars: 
    dir: "{{ item }}"
    extensions:
        - yml  
  with_items:
    - '../defaults/'
    - '../vars/'
  tags:
    - always  

#---Plays---

#---Update Package Lists---

- name: "{{ play_name }}Updating package list for RedHat"
  yum:
    name: '*'
    state: latest
  when: 
    - ansible_os_family == 'RedHat'
    - update == true  
  vars:
    play_name: "Update : "
  tags:
    - setup
    - root
    - update
    - redhat

- name: "{{ play_name }}Updating package cache for Debian"
  apt:
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo
  when: 
    - ansible_os_family == "Debian"
    - update == true
  vars:
    play_name: "Update : "
  tags:
   - setup
   - root
   - update
   - debian
  
#---

#---Install java---

- name: "{{ play_name }}Loading Java Install"
  include: "java.yml"
  when:
    - java == true
  vars:
    play_name: "Java : "
  tags:
    - root
    - java
  
#---

#---Install MySQL---

- name: "{{ play_name }}Loading Pexpect Install"
  include: "pexpect.yml"
  become: yes
  become_user: root
  become_method: sudo
  when:
    - mysql == true
  vars:
    play_name: "MySQl Pexpect : "
  tags:
    - root
    - mysql
    - python
  
- name: "{{ play_name }}Loading MySQl Install and Config"
  include: "mysql.yml"
  become: yes
  become_user: root
  become_method: sudo
  when:
    - mysql == true
  vars:
    play_name: "MySQL : "
  tags:
    - root
    - mysql  

#---

#---Creating non-root user


- name: "{{ play_name }} Creating '{{ user_name }}' with password '{{ user_pass }}'"
  user:
    name: "{{ user_name }}"
    password: "{{ user_pass }}"
    state: present
  when:
    - createuser == true
  tags:
    - createuser

#---

#---Glassfish---

- name: "{{ play_name }}Loading Glassfish install" 
  include: "glassfish.yml" 
  become: yes
  become_user: "{{ user_name }}"
  when:
    - glassfish == true
  vars:
    play_name: "Glassfish : "
  tags:
    - user
    - glassfish

#---

#---Authentication---

- name: "{{ play_name }}Loading Simple Authenticaton install"
  include: "{{ item }}"
  become: yes
  become_user: "{{ user_name }}"
  with_items:
    - authn.yml
  vars:
    play_name: "Authn Simple : "
    authn_plugin: simple
  when:
    - authn == true 
    - authn_simple == true
  tags:
    - user
    - authn
    - simple

- name: "{{ play_name }}Loading DB Authenticaton install"
  include: "{{ item }}"
  become: yes
  become_user: "{{ user_name }}"
  with_items:
    - authn.yml
  vars:
    play_name: "Authn DB : "
    authn_plugin: db
  when: 
    - authn== true 
    - authn_db == true
  tags:
    - user
    - authn
    - db

- name: "{{ play_name }}Loading LDAP Authenticaton install"
  include: "{{ item }}"
  become: yes
  become_user: "{{ user_name }}"
  with_items:
    - authn.yml
  vars:
    play_name: "Authn Ldap : "
    authn_plugin: ldap 
  when: 
    - authn == true
    - authn_ldap == true
  tags:
    - user
    - authn
    - ldap

- name: "{{ play_name }}Loading Anon Authenticaton install"
  include: "{{ item }}"
  become: yes
  become_user: "{{ user_name }}"
  with_items:
    - authn.yml
  vars:
    play_name: "Authn Anon : "
    authn_plugin: anon
  when: 
    - authn == true
    - authn_anon == true
  tags:
    - user
    - authn
    - anon

#---

#---ICATServer---

- name: "{{ play_name }}Loading ICAT server install"
  include: "icatserver.yml"
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "ICAT Server : "
  when:
    - icat == true
  tags:
    - user
    - icat

#---

#---Storage Plugin---Problem with setup script (currently ignored)

- name: "{{ play_name }}Loading Storage Plugin Install"
  include: "storage.yml"
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "IDS Storage : "
  when:
    - storage == true
  tags:
    - user
    - storage

#---

#---IDS---

- name: "{{ play_name }}Loading IDS Install"
  include: "ids.yml"
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "IDS : "
  when:
    - ids == true
  tags:
    - user
    - ids

#---

#---Test Data---ingest script currently forced to timeout (replace with smaller file)

- name: "{{ play_name }}Loading Python Icat Install"
  include: "pycat.yml"
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "TestData : "
  when:
    - testdata == true
  tags:
    - user
    - testdata
    - pycat
    - lorem
  
#---

#---Topcat Interface---

- name: "{{ play_name }}Loading TopCat Install"
  include: "topcat.yml"
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "TopCat : "
  when:
    - topcat == true
  tags:
    - user
    - topcat
  
#---

#---Cleanup---add variables to specify level of cleanup (eg. move all files to single directory or delete all of them)

- name: "Cleanup : Moving all uneeded files to {{ download_dir }}"
  command: "mv -f {{ item }} {{ download_dir }}"
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - "~/{{ pycat_zip }}"
    - "{{ user_home }}/setup-glassfish.py"
    - "{{ user_home }}/lils.yml"
  when: 
    - cleanup == true

#---
