---

- name: "{{ play_name }}Installing python pip"
  package:
    name: python-pip
    state: present

- name: "{{ play_name }}Installing pexpect"
  pip:
    name: pexpect
    state: latest

- name: "{{ play_name }}Checking Python version"
  command: "{{ item }} -V"
  with_items:
    - python
    - pip
