---

- name: "{{ play_name }}Loading Pre-playbook Check"
  include: "preplay.yml"

#---

#---Checking existing facilities---

- name: "{{ play_name }}Getting ICAT session ID"
  command: "curl -k -X POST -d 'json={\"plugin\" : \"{{ icat_mech }}\", \"credentials\" : [{\"username\":\"root\"},{\"password\":\"{{ icat_pass }}\"}]}' {{ icat_url }}/{{ icat_name }}/session"
  register: icat_sess

- set_fact:
     icat_id: "{{ icat_sess.stdout | replace('\":\"','=') | replace('\"','') | replace('{','') | replace('}','') }}"

- debug: msg="{{ item }}"
  with_items:
    - "{{ icat_sess.stdout }}" 
    - "{{ icat_id }}"
  when: '"sessionId" in icat_sess.stdout'

- name: "{{ play_name }}Checking existing facilities"
  command: "curl -k -G --data-urlencode \"{{ icat_id }}\" --data-urlencode \"query=SELECT f from Facility f\" {{ icat_url }}/icat/entityManager"
  register: icat_facs

- debug: var=icat_facs.stdout

#---

#---Deleting Facility if requested---

 #--Wiping ICAT with Python script--

- name: "{{ play_name }}Wiping ICAT"
  command: "wipeicat.py --url \"{{ icat_url }}/ICATService/ICAT?wsdl\" -u {{ icat_root }} -p {{ icat_pass }} -a {{ icat_mech }}"
  when:
    - 'fac_name in icat_facs.stdout'
    - wipe_icat == true

 #--

 #--Deleting from sql script--

- name: "{{ play_name }}Creating SQL Deletion Scripts"
  template:
    src: "../templates/{{ item }}"
    dest: "{{ download_dir }}"
  with_items:
    - idgrab.sql
    - delusers.sql
  when:
    - 'fac_name in icat_facs.stdout'
    - delete_fac == true

- name: "{{ play_name }}Getting {{ fac_name }} ID"
  mysql_db:
    state: import
    target: "{{ download_dir }}idgrab.sql"
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    name: "{{ icat_name }}"
  when:
    - 'fac_name in icat_facs.stdout'
    - delete_fac == true
  register: sql_msg

- set_fact:
    icat_fac_id: "{{ sql_msg.msg | replace('ID','') | replace('\\n','') }}"
  when:
    - 'fac_name in icat_facs.stdout'
    - delete_fac == true

- name: "{{ play_name }}Deleting facility"
  command: "curl -k --get -X DELETE --data-urlencode \"{{ icat_id  }}\" --data-urlencode 'entities={\"Facility\": {\"id\":{{ icat_fac_id }} } }' {{ icat_url }}/{{ icat_name }}/entityManager"  
  when:
    - 'fac_name in icat_facs.stdout'
    - delete_fac == true

- name: "{{ play_name }}Deleting Users"
  mysql_db:
    state: import
    target: "{{ download_dir }}delusers.sql"
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    name: "{{ icat_name }}"
  when:
    - 'fac_name in icat_facs.stdout'
    - delete_fac == true

 #--

- name: "{{ play_name }}Checking existing facilities"
  command: "curl -k -G --data-urlencode \"{{ icat_id }}\" --data-urlencode \"query=SELECT f from Facility f\" {{ icat_url }}/icat/entityManager"
  when:
    - '"sessionId=" in icat_id'
    - 'fac_name in icat_facs.stdout'
    - ( wipe_icat == true ) or ( delete_fac == true )
  register: icat_facs2    

- set_fact:
    icat_facs: "{{ icat_facs2 }}"
  when:
    - '"sessionId=" in icat_id'
    - 'fac_name in icat_facs.stdout'
    - ( wipe_icat == true ) or ( delete_fac == true )

#---

#---Install dependencies for Yum/Apt---

- name: "{{ play_name }}Installing dependencies with Pip"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - suds-jurko
    - PyYAML
  become: yes
  become_user: root
  when: 'fac_name not in icat_facs.stdout'

- name: "{{ play_name }}Installing dependencies with Yum/Apt"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pycat_pkg }}"
  become: yes
  become_user: root
  become_method: sudo
  when:
    - 'fac_name not in icat_facs.stdout'

- name: "{{ play_name }}Checking Python version"
  command: python --version
  register: pyv
  when: 'fac_name not in icat_facs.stdout'

#---

#---Downloading PyCAT---

- stat:
    path: "{{ download_dir }}{{ pycat_zip }}"
  register: pi_zip

- name: "{{ play_name }}Downloading Python ICAT"
  get_url:
    url: "{{ pycat_url }}"
    dest: "{{ download_dir }}"
  when: 
    - 'fac_name not in icat_facs.stdout'
    - pi_zip.stat.exists == false

#---

#---Unzipping PyCAT

- stat:
    path: "{{ pycat_path }}"
  register: pi_dir
  become: yes
  become_user: root
  become_method: sudo

- name: "{{ play_name }}Unzipping {{ pycat_zip }} "
  unarchive:
    src: "{{ download_dir }}{{ pycat_zip }}"
    dest: "/root/"
    owner: root
    group: root
    remote_src: yes
  become: yes
  become_user: root
  become_method: sudo
  when: 
    - 'fac_name not in icat_facs.stdout'
    - pi_dir.stat.exists == false

#---

#---Patching for Python 2.6---

- name: "{{ play_name }}Patching for Python 2.6"
  patch:
    src: "{{ pycat_path }}/python2_6.patch"
    basedir: "{{ pycat_path }}/"
    remote_src: yes
    strip: 1
  become: yes
  become_user: root
  become_method: sudo
  when: 
    - 'fac_name not in icat_facs.stdout'
    - '"2.6." in pyv.stderr'

#---

#---Installing PyCAT---

- name: "{{ play_name }}Building and Installing Python ICAT"
  command: "python setup.py {{ item }}"
  args:
    chdir: "{{ pycat_path }}"
  with_items:
    - build
    - install
  become: yes
  become_user: root
  become_method: sudo
  when: 'fac_name not in icat_facs.stdout'

#---Populating Database---

- stat:
    path: "{{ download_dir }}lils.yml"
  register: pi_lils

- name: "{{ play_name }}Copying Dump file"
  copy:
    src: ../files/lils.yml
    dest: "{{ download_dir }}lils.yml"
    force: no
  when: 
    - 'fac_name not in icat_facs.stdout'
    - pi_lils.stat.exists == false

- name: "{{ play_name }}Modifying dump file"
  replace:
    path: "{{ download_dir }}lils.yml"
    regexp: "simple"
    replace: "{{ icat_mech }}"
  when:
    - 'fac_name not in icat_facs.stdout'

#TODO-create smaller file so forced timeout is not required

- name: "{{ play_name }}Running ICAT ingest"
  command: "icatingest.py --url {{ icat_url }}/ICATService/ICAT?wsdl -u root -p {{ icat_pass }} -i {{ download_dir }}lils.yml -a {{ icat_mech }}"
  when: 
    - 'fac_name not in icat_facs.stdout'
  ignore_errors: yes
  async: 60
  poll: 5

#---

#---Creating Files---  
 
- name: "{{ play_name }}Creating Datafile grab script"
  template:
    src: "../templates/datafile_grab.sql"
    dest: "{{ download_dir }}"
  when:
    - 'fac_name not in icat_facs.stdout'
    - (create_file == true) or (create_all == true)

 #--Create 'Datafile 1' files--

- name: "{{ play_name }}Writing Datafile grab script for only '{{ datafile }}' files"
  lineinfile:
    path: "{{ download_dir }}datafile_grab.sql"
    regexp: "^select"
    line: "select LOCATION from DATAFILE where NAME = \"{{ item }}\";"
    state: present
  with_items:
    - "{{ datafiles }}"
  when:
    - 'fac_name not in icat_facs.stdout'
    - create_file == true

 #--Create ALL files--

- name: "{{ play_name }}Getting Datafiles"
  mysql_db:
    state: import
    target: "{{ download_dir }}datafile_grab.sql"
    login_user: "root"
    login_password: "{{ mysql_root_pass }}"
    name: "{{ icat_name }}"
  when:
    - (create_file == true) or (create_all == true)
  register: datafile_string

- set_fact:
    datafile_list: "{{ datafile_string.msg | replace('LOCATION','') }}"
  when:
    - 'fac_name not in icat_facs.stdout'
    - (create_file == true) or (create_all == true)

- set_fact:
    datafile_list: "{{ datafile_list.split('\n') }}"
  when:
    - 'fac_name not in icat_facs.stdout'
    - (create_file == true) or (create_all == true)
        

#--CREATING DATAFILES--

- name: "{{ play_name }}Making Directories"
  file:
    state: directory
    name: "{{ user_home }}/{{ icat_name }}/main/{{ item | dirname }}"
    recurse: yes
  with_items:
    - "{{ datafile_list }}"
  when:
    - 'fac_name not in icat_facs.stdout'
    - (create_file == true) or (create_all == true)

- name: "{{ play_name }}Creating files"
  file:
    state: touch
    name: "{{ user_home }}/{{ icat_name }}/main/{{ item }}"
  with_items:
    - "{{ datafile_list }}"
  when:
    - 'fac_name not in icat_facs.stdout'
    - (create_file == true) or (create_all == true)

#---


