---

- name: "{{ play_name }}Installing Dependencies for Yum"
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - firefox
    - xorg-x11-server-Xvfb
  when:
    - ansible_pkg_mgr == "yum"

- name: "{{ play_name }}Installing Dependencies for Apt"
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - firefox
    - xvfb
  when:
    - ansible_pkg_mgr == "apt"


- name: "{{ play_name }}Installing dependencies with Pip"
  pip:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - pyvirtualdisplay
    - selenium

- name: "{{ play_name }}Creating test directories"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ download_dir }}"
    - "{{ test_dir }}"

- name: "{{ play_name }}Downloading Webdrivers"
  get_url:
    url: "{{ item }}"
    dest: "{{ download_dir }}"
  with_items:
    - "{{ geckodriver_src }}"
    - "{{ chromedriver_src }}"

- name: "{{ play_name }}Unzipping Webdrivers"
  unarchive:
    src: "{{ download_dir }}{{ item }}"
    dest: "{{ test_dir }}"
    remote_src: yes
  with_items:
    - "{{ geckodriver_zip }}"
    - "{{ chromedriver_zip }}"

- name: "{{ play_name }}Copying Selenium Script and geckodriver workaround script"
  copy:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ test_dir }}/"
    mode: "{{ item.mode }}"
  with_items:
    - { src: topcat_test.py,  mode: "u=rw,g=rw,o=rw" }
    - { src: gecko.sh,        mode: "u=rwx,g=rwx,o=rwx" }

- name: "{{ play_name }}Creating Blank files with travis friendly permissions"
  file:
    path: "{{ test_dir }}/{{ item }}"
    state: touch
    mode: "u=rw,g=rw,o=rw"
  with_items:
    - geckodriver.log
    - topcat_test_output

- name: "{{ play_name }}Templating Arguments for Selenium Script"
  template:
    src: "{{ role_path }}/files/test_args.txt"
    dest: "{{ test_dir }}/"
