---

- name: "{{ play_name }}Starting {{ container_domain }} before tasks"
  include: "startdomain.yml"

#---

- name: "{{ play_name }}Changing URL and filenames for versions 1.4.0 and later"
  set_fact:
    sub_domain: repo
    url_mvn: 
    storage_setup: setup.properties
  when:
    - storage_version | version_compare('1.4.0', '>=')

- name: "{{ play_name }}Changing url for versions older than 1.4.0"
  set_fact:
    sub_domain: www
    url_mvn: mvn/
    storage_setup: ids.storage_file-setup.properties
  when:
    - storage_version | version_compare('1.4.0', '<') == true

#---



#---Downloading Storage plugin---

- name: "{{ play_name }}Downloading IDS Storage Plugin"
  include: "download.yml"
  vars:
    - download_zip: "{{ storage_zip }}"
    - download_src: "{{ storage_src }}"
    - download_path: "{{ storage_path }}"
    - download_dest: "{{ user_home }}"

#---

#---Creating Directories---

- name: "{{ play_name }}Making directories to store data - '{{ dir_main }}' and '{{ dir_archive }}'"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dir_main }}"
    - "{{ dir_archive }}"

#---

#---Properties files---

- name: "{{ play_name }}Creating directory properties files for versions older than 1.4.0"
  file:
    path: "{{ storage_path }}/{{ item }}"
    state: touch
  with_items:
    - "{{ storage_main }}"
    - "{{ storage_archive }}"
  when:
    - storage_version | version_compare('1.4.0', '<') == true
  
- name: "{{ play_name }}Configuring directory properties files for versions older than 1.4.0"
  lineinfile:
    path: "{{ storage_path }}/{{ item.file }}"
    regexp: "dir="
    line: "{{ item.line }}"
  with_items:
    - { file: "{{ storage_main }}",    line: "dir = {{ dir_main }}" }
    - { file: "{{ storage_archive }}", line: "dir = {{ dir_archive }}" }
  when:
    - storage_version | version_compare('1.4.0', '<') == true

#---Setup Properties---

- name: "{{ play_name }}Copying {{ storage_setup }}.example"
  copy:
    src: "{{ storage_path }}/{{ storage_setup }}.example"
    dest: "{{ storage_path }}/{{ storage_setup }}"
    remote_src: yes

- name: "{{ play_name }}Configuring {{ storage_setup }}"
  lineinfile:
    path: "{{ storage_path }}/{{ storage_setup }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ container_cnf_list }}"

#---


#---Running Setup---

#NOTE
#This task needs work as it returns errors on the first run, however the setup is actually succesful.
#Currently it simply ignores errors, this is not ideal as any genuine errors will be ignored.

- name: "{{ play_name }}Installing IDS Storage"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ glassfish_path }}/bin"
  shell:
    cmd: ./setup install
    chdir: "{{ storage_path }}"
  ignore_errors: yes
  tags:
    - install

#---
