---

#---Dependencies---

#-Xvfb-
 # Used by pyvirtual display

- name: "{{ play_name }}Installing Dependencies for Yum"
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - xorg-x11-server-Xvfb
  when:
    - ansible_pkg_mgr == "yum"

- name: "{{ play_name }}Installing Dependencies for Apt"
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - xvfb
  when:
    - ansible_pkg_mgr == "apt"

#-pyvirtualdisply-
 # Used when GUI is unavailiable

- name: "{{ play_name }}Installing dependencies with Pip"
  pip:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - pyvirtualdisplay
    - selenium

#---

#---Download Topcat_Selenium---

- name: "{{ play_name }}Making Test directory"
  file:
    path: "{{ ts_path }}"
    state: directory

- name: "{{ play_name }}Getting selenium script"
  get_url:
    url: "{{ ts_url }}"
    dest: "{{ ts_path }}/"

#---

#---Template Arguments---

- name: "{{ play_name }}Templating Arguments for Selenium Script"
  template:
    src: "{{ role_path }}/templates/test_args"
    dest: "{{ ts_path }}/"

#---
