---

#---Dependencies---

#-Xvfb-
 # Used by pyvirtual display

- name: "{{ play_name }}Installing Dependencies for Yum"
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - xorg-x11-server-Xvfb
  when:
    - ansible_pkg_mgr == "yum"

- name: "{{ play_name }}Installing Dependencies for Apt"
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - xvfb
  when:
    - ansible_pkg_mgr == "apt"

#-pyvirtualdisply-
 # Used when GUI is unavailiable

- name: "{{ play_name }}Installing dependencies with Pip"
  pip:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  with_items:
    - pyvirtualdisplay
    - selenium

#---


#---Browsers--

#-Firefox-

- name: "{{ play_name }}Installing Firefox"
  package:
    name: firefox
    state: present
  become: yes
  become_user: root
  become_method: sudo
  when:
    - firefox == true


#-Chrome-


# TODO - get yum install google-chrome-stable working
#
#- name: "{{ play_name }}Creating google.repo file in /etc/yum.repos.d/ for yum"
#  file:
#    path: /etc/yum.repos.d/google.repo
#    state: touch
#  become: yes
#  become_user: root
#  become_method: sudo
#  when:
#    - ansible_pkg_mgr == 'yum'
#    - chrome == true
 
#- name: "{{ play_name }}Adding google repo to google.repo file for yum"
#  blockinfile:
#    path: /etc/yum.repos.d/google.repo
#    state: present
#    marker: '##{mark}'
#    block: |
#      [google-chrome]
#      name=google-chrome - \$basearch
#      baseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch
#      enabled=1
#      gpgcheck=1
#      gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
#  become: yes
#  become_user: root
#  become_method: sudo
#  when:
#    - ansible_pkg_mgr == 'yum'
#    - chrome == true


- name: "{{ play_name }}Get Key for chrome for apt"
  apt_key: 
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes
  become_user: root
  become_method: sudo
  when:
    - ansible_pkg_mgr == 'apt'
    - chrome == true

- name: "{{ play_name }}Add chrome repo to apt"
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo
  when:
    - ansible_pkg_mgr == 'apt'
    - chrome == true


- name: "{{ play_name }}Install Chrome"
  package:
    name: google-chrome-stable
    state: present
  become: yes
  become_user: root
  become_method: sudo
  when:
    - chrome == true
    - ansible_pkg_mgr == 'apt'
# Uncomment pkg_mgr conditional once yum chrome works


#---

#---Download Topcat_Selenium---

- name: "{{ play_name }}Downloading Topcat_Selenium"
  include: include_download.yml
  vars:
    - download_zip: "{{ ts_zip }}"
    - download_src: "{{ ts_src }}"
    - download_path: "{{ ts_path }}"
    - download_dest: "{{ user_home }}"

#---

#---

  # In theory these files should be created automatically by geckodriver and travis
  # But I've had instances where errors have been thrown because they are trying to write to a file that doesn't exist or a file that's owned by a different user
  # So to be safe I've added this task to create blank files with rw permisions for everyone to write to
- name: "{{ play_name }}Creating Blank files with travis friendly permissions"
  file:
    path: "{{ ts_path }}/{{ item }}"
    state: touch
    mode: "u=rw,g=rw,o=rw"
  with_items:
    - geckodriver.log
    - topcat_test_output

#---

#---Template Arguments---

  # This is the only task that has to be run by ansible since it uses the variables from ansible
  # All other tasks in this file could, in theory be performed by travis or the selenium script
- name: "{{ play_name }}Templating Arguments for Selenium Script"
  template:
    src: "{{ role_path }}/templates/test_args"
    dest: "{{ ts_path }}/"

#---
