---
# vars file for /etc/ansible/roles/IDS/

#IDS zip
ids_src: http://www.icatproject.org/mvn/repo/org/icatproject/ids.storage_file/1.3.3/ids.storage_file-1.3.3-distro.zip
ids_zip: ids.storage_file-1.3.3-distro.zip

#Directories
dir_main: /home/{{ user_name }}/{{ mysql_db_name }}/main
dir_archive: /home/{{ user_name }}/{{ mysql_db_name }}/archive

#properties
ids_main_prop: ids.storage_file.main.properties 
ids_archive_prop: ids.storage_file.archive.properties 
ids_setup_prop: ids.storage_file-setup.properties
