---

- name: Checking download directory
  file:
    path: "{{ download_dir }}"
    state: directory

- name: Downloading Glassfish
  get_url:
    url: "{{ glassfish_src }}"
    dest: "{{ download_dir }}"
    
- name: Unzipping {{ glassfish_zip }} 
  unarchive:
    src: "{{ download_dir }}{{ glassfish_zip }}"
    dest: "/home/{{ user_name }}/"
    remote_src: yes

- name: Downloading Glassfish setup script#
  get_url:
    url: "{{ glassfish_setup }}"
    dest: "/home/{{ user_name }}"

- name: Running setup script
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ user_name }}/glassfish4/bin"
  command: python setup-glassfish.py {{ glassfish_domain }} 75% {{ mysql_root_pass }}

- name: Configuring Glassfish for MySQL
  copy:
    src: "{{ glassfish_java }}"
    dest: "/home/{{ user_name }}/glassfish4/glassfish/domains/{{ glassfish_domain }}/lib/ext/"
    remote_src: yes

- name: Restarting {{ glassfish_domain }}
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ user_name }}/glassfish4/bin"
  command: "nohup {{ item }}"
  with_items:
  - "asadmin stop-domain {{ glassfish_domain }}"
  - "asadmin start-domain {{ glassfish_domain }}"
#  - "asadmin restart-domain {{ glassfish_domain}}"
  - "asadmin list-domains"

