---
- name: Installing MySQL Packages - Specifically '{{ mysql_packages }}' 
  yum: 
    name: "{{ mysql_packages }}" 
    state: latest 

- name: Configuring MySQL - Removing default engine setting 
  lineinfile: 
    path: "{{ mysql_cnf_path }}" 
    state: absent 
    regexp: 'default_storage_engine =' 
    
- name: Configuring MySQL - Setting default engine to '{{ mysql_cnf_eng }}' 
  lineinfile: 
    path: /etc/my.cnf 
    insertafter: '[mysqld] ' 
    line: default_storage_engine = {{ mysql_cnf_eng }} 
 
- name: Confuguring MySQL - Starting database 
  service: 
    name: mysqld 
    state: started 
     
- name: Configuring MySQL - Running '{{ mysql_secure }}' 
  expect: 
    command: "{{ mysql_secure }}" 
    responses: 
      password: "pw" 
      Question: 
        - y 
        - "{{ mysql_root_pass }}" 
        - "{{ mysql_root_pass }}" 
        - y 
        - n 
        - y 
        - y  
 
- name: Creating MySQL Database - {{ mysql_db_name }} 
  mysql_db: 
    login_user: root 
    login_password: "{{ mysql_root_pass }}" 
    name: "{{ mysql_db_name }}" 
    state: present 
 
- name: Creating Database login - user={{ mysql_user_name }} pass={{ mysql_user_pass }} 
  mysql_user: 
    login_user: root 
    login_password: "{{ mysql_root_pass }}" 
    name: "{{ mysql_user_name }}" 
    password: "{{ mysql_user_pass }}" 
    priv: '*.*:ALL,GRANT' 
    state: present 
