---
# tasks file for /etc/ansible/roles/TopCat/

- name: Downloading {{ topcat_zip }}
  get_url:
    url: "{{ topcat_src }}"
    dest: "{{ download_dir }}"
    
- name: Unzipping {{ topcat_zip }}
  unarchive:
    src: "{{ download_dir }}{{ topcat_zip }}"
    dest: "/home/{{ user_name }}/"
    remote_src: yes

- name: Creating {{ topcat_setup }}
  file:
    path: "/home/{{ user_name }}/topcat/{{ topcat_setup }}"
    state: touch

- name: Configuring {{ topcat_setup }}
  blockinfile:
    path: "/home/{{ user_name }}/topcat/{{ topcat_setup }}"
    block: |
      {{ glassfish_cnf }}    
      {{ mysql_cnf }}
      {{ email_cnf }}
      
- name: Creating {{ topcat_prop }}
  copy:
    src: "/home/{{ user_name }}/topcat/{{ topcat_prop }}.example"
    dest: "/home/{{ user_name }}/topcat/{{ topcat_prop }}"
    remote_src: yes
  
- name: Configuring {{ topcat_prop }}
  lineinfile:
    path: "/home/{{ user_name }}/topcat/{{ topcat_prop }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "mail.enable",    line: "mail.enable = {{ mail_enable }}"}
    - { regexp: "ids.getstatus",  line: "ids.getStatus.max = 100" }
    - { regexp: "poll.delay",     line: "poll.delay = 600" }
    - { regexp: "poll.interval",  line: "poll.interval.wait = 600" }
    - { regexp: "adminUserNames", line: "adminUserNames = simple/root" }

- name: Creating files - {{ topcat_json }}, {{ topcat_lang }} and {{ topcat_css }}
  copy:
    src: "/home/{{ user_name}}/topcat/{{ item }}.example"
    dest: "/home/{{ user_name}}/topcat/{{ item }}"
    remote_src: yes
  with_items:
    - "{{ topcat_json }}"
    - "{{ topcat_lang }}"
    - "{{ topcat_css }}"

- name: Configuring {{ topcat_json }}
  replace:
    path: "/home/{{ user_name }}/topcat/{{ topcat_json }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.rep }}"
  with_items:
    - { regexp: "https", rep: "http" }
    - { regexp: "8181",  rep: "8080" }
    - { regexp: 'your facility name[^"]*', rep: "LILS" }

- name: Running Setup
  shell:
    cmd: ./setup install
    chdir: "/home/{{ user_name }}/topcat"

