---

- name: "{{ play_name }}Installing Ruby Dependencies - Specifically '{{ ruby_packages }}'"
  yum:
    name: "{{ ruby_packages }}"
    state: latest
  become: yes
  become_user: root
  become_method: sudo

- name: "{{ play_name }}Installing 'Ruby 2.3.1' via rvm"
  shell:
    cmd: "{{ item }}"
  with_items:
    - curl -sSL https://get.rvm.io | bash
#    - source /home/{{ user_name }}/.rvm/scripts/rvm
    - /home/{{ user_name }}/.rvm/bin/rvm install --default 2.3.1 
    - /home/{{ user_name }}/.rvm/scripts/rvm gem install faker rest-client

- name: "{{ play_name }}Downloading Lorem Ipsum script to '{{ download-dir }}'"
  get_url:
    url: "{{ lorem_src }}"
    dest: "{{ download_dir }}"

- name: "{{ play_name }}Moving {{ lorem_script }} to home directory as {{ lorem_script_edit }}"
  copy:
    src: "{{ download_dir }}{{ lorem_script }}"
    dest: "/home/{{ user_name }}/{{ lorem_script_edit }}"
    remote_src: yes

- name: "{{ play_name }}Rewriting script" 
  lineinfile:
    path: "/home/{{ user_name }}/{{ lorem_script_edit }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: "password =>",  line: "{:password => {{ mysql_root_pass }}}"}
#    - {regexp: "name  

- name: "{{ play_name}}Running Lorem Ipsum Script to populate Icat database"
  shell:  
    cmd: "/home/{{ user_name }}/.rvm/scripts/rvm {{ lorem_script_edit }}"
    chdir: "/home/{{ user_name }}"
