---

- name: "{{ play_name }}Checking download directory '{{ download_dir }}' - Creating if non existent"
  file:
    path: "{{ download_dir }}"
    state: directory

- name: "{{ play_name }}Downloading '{{ storage_zip }}' to '{{ download_dir }}'"
  get_url:
    url: "{{ storage_src }}"
    dest: "{{ download_dir }}"

- name: "{{ play_name }}Unziping {{ storage_zip }} to '/home/{{ user_name }}/'"
  unarchive:
    src: "{{ download_dir }}{{ storage_zip }}"
    dest: "/home/{{ user_name }}/"
    remote_src: yes

- name: "{{ play_name }}Making directories to store data - '{{ dir_main }}' and '{{ dir_archive }}'"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dir_main }}"
    - "{{ dir_archive }}"

- name: "{{ play_name }}Creating properties files in '/home/{{ user_name }}/ids.storage_file/'"
  file:
    path: "/home/{{ user_name }}/ids.storage_file/{{ item }}"
    state: touch
  with_items:
    - "{{ storage_main }}"
    - "{{ storage_archive }}"
    - "{{ storage_setup }}"
  
- name: "{{ play_name }}Configuring properties files - Adding storage directories"
  lineinfile:
    path: "/home/{{ user_name }}/ids.storage_file/{{ item.file }}"
    regexp: "dir="
    line: "{{ item.line }}"
  with_items:
    - { file: "{{ storage_main }}", line: "dir={{ dir_main }}" }
    - { file: "{{ storage_archive }}", line: "dir={{ dir_archive }}" }

- name: "{{ play_name }}Configuring {{ storage_setup }} - Adding Glassfish block"
  blockinfile:
    path: "/home/{{ user_name }}/ids.storage_file/{{ storage_setup }}"
    block: "{{ glassfish_cnf }}"

- name: "{{ play_name }}Installing IDS Storage"
  shell:
    cmd: ./setup install
    chdir: "/home/{{ user_name }}/ids.storage_file"
