---
# vars file for /etc/ansible/roles/ICAT

#Download URL for ICAT zip
icat_src: https://repo.icatproject.org/repo/org/icatproject/icat.server/4.8.0/icat.server-4.8.0-distro.zip

#zip file for ICAT
icat_zip: icat.server-4.8.0-distro.zip

#Icat setup properties
icat_setup: icat-setup.properties

#Lucene
lucene_dir: /home/{{ user_name }}/icat/data/lucene
