---

- name: "{{ play_name }}Setting variables for RedHat"
  set_fact:
     script_path: setup-glassfish.py
     glassfish_java: "{{ glassfish_java_redhat }}"
  when: ansible_os_family == "RedHat"
  tags:
    - redhat

- name: "{{ play_name }}Setting variable for Debian"
  set_fact:
    script_path: "~/setup-glassfish.py"
    glassfish_java: "{{ glassfish_java_debian }}"
  when: ansible_os_family == "Debian"   

- name: "{{ play_name }}Checking download directory"
  file:
    path: "{{ download_dir }}"
    state: directory

- name: "{{ play_name }}Downloading Glassfish"
  get_url:
    url: "{{ glassfish_src }}"
    dest: "{{ download_dir }}"

- name: "{{ play_name }}Unzipping {{ glassfish_zip }}"
  unarchive:
    src: "{{ download_dir }}{{ glassfish_zip }}"
    dest: "/home/{{ user_name }}/"
    remote_src: yes

- name: "{{ play_name }}Downloading Glassfish setup script"
  get_url:
    url: "{{ glassfish_setup }}"
    dest: "/home/{{ user_name }}"

- name: "{{ play_name }}Running setup script"
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ user_name }}/glassfish4/bin"
  command: python {{ script_path }} {{ glassfish_domain }} 75% {{ mysql_root_pass }}

- name: "{{ play_name }}Configuring Glassfish for MySQL"
  copy:
    src: "{{ glassfish_java }}"
    dest: "/home/{{ user_name }}/glassfish4/glassfish/domains/{{ glassfish_domain }}/lib/ext/"
    remote_src: yes

- name: "{{ play_name }}Restarting {{ glassfish_domain }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ user_name }}/glassfish4/bin"
  command: "nohup {{ item }}"
  with_items:
  - "asadmin restart-domain {{ glassfish_domain }}"
  - "asadmin list-domains"
   
