---
#Master file for ICATInstall

#---NOTES---
#Variables are currently stored in a single YAML file, these should be separated by OS (eg. Ubuntu, Debian etc) or by function (eg. logins, package versions etc)

#---TODO---
# Check which plays need separate install for other OSs
# Organise variables for easy customisation
# Improve non-fresh install checking to skip tasks rather than ignoring errors (see mysql.yml and storage.yml)
# Improve feedback
# Add autotests


#---Plays---

#---Update Package Lists---This seems to break stfc cloud vms, use with caution

- name: "{{ play_name }}Updating package list for RedHat"
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == 'RedHat'
  vars:
    play_name: "Update : "
  tags:
    - setup
    - root
    - update
    - redhat
    - tested

- name: "{{ play_name }}Updating package cache for Debian"
  apt:
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"
  vars:
    play_name: "Update : "
  tags:
   - setup
   - root
   - update
   - debian
   - tested

#---

#---Install java---

- name: "{{ play_name }}Loading Java Install"
  include: "java.yml"
  vars:
    play_name: "Java : "
  tags:
    - root
    - java
    - tested

#---

#---Install MySQL---

- name: "{{ play_name }}Loading Pexpect Install"
  include: "pexpect.yml"
  vars:
    play_name: "MySQl Pexpect : "
  tags:
    - root
    - mysql
    - python
    - tested

- name: "{{ play_name }}Loading MySQl Install and Config"
  include: "mysql.yml"
  vars:
    play_name: "MySQL : "
  tags:
    - root
    - mysql  
    - tested

#---

#---Creating non-root user

- name: "{{ play_name }}Loading Non-Root User Creation"
  include: "user.yml"
  vars:
    play_name: "Non-Root User : "
  tags:
    - createuser
    - tested

#---

#---Glassfish---

- name: "{{ play_name }}Loading Glassfish install" 
  include: "glassfish.yml" 
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "Glassfish : "
  tags:
    - user
    - glassfish
    - tested

#---

#---Authentication---

- name: "{{ play_name }}Loading Simple Authenticaton install"
  include: "simpleauthn.yml"
  become: yes
  become_user: "{{ user_name }}"
  when: authn_simple == true
  vars:
    play_name: "Authn Simple : "
  tags:
    - user
    - authn
    - simple
    - tested

- name: "{{ play_name }}Loading DB Authenticaton install"
  include: "dbauthn.yml"
  become: yes
  become_user: "{{ user_name }}"
  when: authn_db == true
  vars:
    play_name: "Authn DB : "
  tags:
    - user
    - authn
    - db
    - tested

- name: "{{ play_name }}Loading LDAP Authenticaton install"
  include: "ldapauthn.yml"
  become: yes
  become_user: "{{ user_name }}"
  when: authn_ldap == true
  vars:
    play_name: "Authn LDAP : "
  tags:
    - user
    - authn
    - ldap
    - tested


- name: "{{ play_name }}Loading Anonymous Authenticaton install"
  include: "anonauthn.yml"
  become: yes
  become_user: "{{ user_name }}"
  when: authn_anon == true
  vars:
    play_name: "Authn anon : "
  tags:
    - user
    - authn
    - anon
    - tested



#---

#---ICATServer---

- name: "{{ play_name }}Loading ICAT server install"
  include: "icatserver.yml"
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "ICAT Server : "
  tags:
    - user
    - icat
    - tested

#---

#---Storage Plugin---Problem with setup script (currently ignored)

- name: "{{ play_name }}Loading Storage Plugin Install"
  include: "storage.yml"
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "IDS Storage : "
  tags:
    - user
    - storage
    - tested

#---

#---IDS---

- name: "{{ play_name }}Loading IDS Install"
  include: "ids.yml"
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "IDS : "
  tags:
    - user
    - ids
    - tested

#---

#---Test Data---ingest script currently forced to timeout (replace with smaller file)

- name: "{{ play_name }}Loading Python Icat Install"
  include: "pycat.yml"
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "TestData : "
  tags:
    - user
    - pycat
    - lorem
    - broken
  
#---

#---Topcat Interface---

- name: "{{ play_name }}Loading TopCat Install"
  include: "topcat.yml"
  become: yes
  become_user: "{{ user_name }}"
  vars:
    play_name: "TopCat : "
  tags:
    - user
    - topcat
    - tested

#---

#---Cleanup---add variables to specify level of cleanup (eg. move all files to single directory or delete all of them)

- name: "Cleanup : Removing uneeded files"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ download_dir }}"
    - "/home/{{ user_name }}/setup-glassfish.py"
    - "/home/{{ user_name }}/{{ lorem_script_edit }}"
  when: cleanup == true
  vars:
    cleanup: false
  tags:
    - user
    - cleanup

#---
