---

- name: "{{ play_name }}Getting ICAT session ID"
  command: "{{ pycat_login }}"
  register: icat_sess


- set_fact:
     icat_id: "{{ icat_sess.stdout | replace('\":\"','=') | replace('\"','') | replace('{','') | replace('}','') }}"

- debug: msg="{{ item }}"
  with_items:
    - "{{ icat_sess.stdout }}" 
    - "{{ icat_id }}"
  when: '"sessionId" in icat_sess.stdout'

- name: "{{ play_name }}Checking existing facilities"
  command: "{{ pycat_check }}"
  register: icat_facs
#  when: '"sessionId=" in icat_id'

#---Delete Facility
#---TODO---Find less destructive deletion method

- set_fact:
     icat_fac_id: "{{ icat_facs.stdout[19:21] }}"  #Improve this
  when: 
    - '"LILS" in icat_facs.stdout'
    - delete_fac == true

- name: "{{ play_name }}Deleting LILS facility if requested"
  command: "{{ pycat_delete }}"
  when: 
    - '"LILS" in icat_facs.stdout'
    - delete_fac == true

- name: "{{ play_name }}Wiping ICAT"
  command: "wipeicat.py --url \"http://localhost:8080/ICATService/ICAT?wsdl\" -u root -p {{ mysql_root_pass }} -a simple"
  when:
    - '"LILS" in icat_facs.stdout'
    - wipe_icat == true

- name: "{{ play_name }}Checking existing facilities"
  command: "{{ pycat_check }}"
  when: '"sessionId=" in icat_id'

#---


- name: "{{ play_name }}Downloading Python ICAT"
  get_url:
    url: "{{ pycat_url }}"
    dest: /root/
  become: yes
  become_user: root
  become_method: sudo
  when: '"LILS" not in icat_facs.stdout'

- name: "{{ play_name }}Unzipping {{ pycat_zip }}"
  unarchive:
    src: "{{ pycat_zip }}"
    dest: "/root/"
    owner: root
    group: root
  become: yes
  become_user: root
  become_method: sudo
  when: '"LILS" not in icat_facs.stdout'

- name: "{{ play_name }}Installing dependencies"
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - suds-jurko
    - PyYAML
  become: yes
  become_user: root
  when: '"LILS" not in icat_facs.stdout'

- name: "{{ play_name }}Installing dependencies for RedHat"
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-argparse
    - python-lxml
  become: yes
  become_user: root
  become_method: sudo
  when: 
    - ansible_os_family == "RedHat"
    - '"LILS" not in icat_facs.stdout'
  tags:
    - redhat

- name: "{{ play_name }}Installing dependencies for Debian"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-argparse
    - python-lxml
  become: yes
  become_user: root
  become_method: sudo
  when: 
    - ansible_os_family == "Debian"
    - '"LILS" not in icat_facs.stdout'
  tags:
    - debian

- name: "{{ play_name }}Checking Python version"
  command: python --version
  register: pyv
  when: '"LILS" not in icat_facs.stdout'

- name: "{{ play_name }}Patching for Python 2.6"
  patch:
    src: "{{ pycat_path }}/python2_6.patch"
    basedir: "{{ pycat_path }}/"
    remote_src: yes
    strip: 1
  become: yes
  become_user: root
  become_method: sudo
  when: 
    - '"LILS" not in icat_facs.stdout'
    - '"2.6." in pyv.stderr'

- name: "{{ play_name }}Building and Installing Python ICAT"
  command: "python setup.py {{ item }}"
  args:
    chdir: "{{ pycat_path }}"
  with_items:
    - build
    - install
  become: yes
  become_user: root
  become_method: sudo
  when: '"LILS" not in icat_facs.stdout'

- name: "{{ play_name }}Copying Dump file"
  copy:
    src: ../files/lils.yml
    dest: "/home/{{ user_name }}/"
  when: '"LILS" not in icat_facs.stdout'

- name: "{{ play_name }}Running ICAT ingest"
  command: 'icatingest.py --url "http://localhost:8080/ICATService/ICAT?wsdl" -u root -p {{ mysql_root_pass }} -i ~/lils.yml -a simple'
  when: '"LILS" not in icat_facs.stdout'
  ignore_errors: yes
  async: 60
  poll: 5
