---

- name: "{{ play_name }}Downloading ruby dependencies for RedHat"
  yum:
    name: "{{ ruby_packages }}"
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"
  tags:
   - redhat
#   - tested

- name: "{{ play_name }}Downloading ruby dependencies for Debian"
  apt:
    name: "{{ ruby_packages }}"
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"
  tags:
   - debian
#   - tested

- name: "{{ play_name }}Installing 'Ruby 2.3.1' via rvm"
  shell:
    cmd: "{{ item }}"
  with_items:
    - curl -sSL {{ rvm_url }} | bash
    - source /home/{{ user_name }}/.rvm/scripts/rvm
    - /home/{{ user_name }}/.rvm/bin/rvm install 2.3.1 --default
    - /home/{{ user_name }}/.rvm/bin/rvm current
    - gem install faker rest-client

#- name: "{{ play_name }}Installing faker and rest-client"
#  gem:
#    name: "{{ item }}"
#    state: latest
#  with_items:
#    - faker
#    - rest-client
