---

- name: "{{ play_name }}Loading Pre-playbook Check"
  include: "preplay.yml"

#---

#---Downloading Simple Authn---

- stat:
    path: "{{ download_dir }}{{ authn_zip_s }}"
  register: sa_zip

- name: "{{ play_name }}Downloading {{ authn_zip_s }}"
  get_url:
    url: "{{ authn_src_s }}"
    dest: "{{ download_dir }}"
  when: sa_zip.stat.exists == false

#---

#---Unzipping Simple Authn---

- stat:
    path: "{{ authn_path_s }}"
  register: sa_dir

- name: "{{ play_name }}Unzipping {{ authn_zip_s }}"
  unarchive:
    src: "{{ download_dir }}{{ authn_zip_s }}"
    dest: "{{ user_home }}"
    remote_src: yes
  when: sa_dir.stat.exists == false

#---

#---Setup-Properties---

- name: "{{ play_name }}Creating {{ authn_setup_s }}"
  file:
    path: "{{ authn_path_s }}/{{ authn_setup_s }}"
    state: touch

- name: "{{ play_name }}Configuring {{ authn_setup_s }}"
  blockinfile:
    path: "{{ authn_path_s }}/{{ authn_setup_s }}"
    block: |
      {{ glassfish_cnf }}

#---

#---Properties---

- name: "{{ play_name }}Creating {{ authn_prop_s }}"
  file:
    path: "{{ authn_path_s }}/{{ authn_prop_s }}"
    state: touch

- name: "{{ play_name }}Creating usernames and passwords in {{ authn_prop_s }}"
  blockinfile:
    path: "{{ authn_path_s }}/{{ authn_prop_s }}"
    block: "{{ authn_block_s }}"
      
#---

#---Running Setup---

- name: "{{ play_name }}Installing Simple Authentication"
  shell:
    cmd: ./setup install
    chdir: "{{ authn_path_s }}"

#---
