---

- name: "{{ play_name }}Starting {{ glassfish_domain }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ user_name }}/glassfish4/bin"
  command: "nohup {{ item }}"
  with_items:
  - "asadmin restart-domain {{ glassfish_domain }}"
  - "asadmin list-domains"

- name: "{{ play_name }}Checking download directory"
  file:
    path: "{{ download_dir }}"
    state: directory

#---Downloading Simple Authn---

- stat:
    path: "{{ download_dir }}{{ authn_zip }}"
  register: sa_zip

- name: "{{ play_name }}Downloading {{ authn_zip }}"
  get_url:
    url: "{{ authn_src }}"
    dest: "{{ download_dir }}"
  when: sa_zip.stat.exists == false

#---

#---Unzipping Simple Authn---

- stat:
    path: "/home/{{ user_name }}/authn.simple"
  register: sa_dir

- name: "{{ play_name }}Unzipping {{ authn_zip }}"
  unarchive:
    src: "{{ download_dir }}{{ authn_zip }}"
    dest: "/home/{{ user_name }}"
    remote_src: yes
  when: sa_dir.stat.exists == false

#---

#---Setup-Properties---

- name: "{{ play_name }}Creating {{ authn_setup_prop }}"
  file:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_setup_prop }}"
    state: touch

- name: "{{ play_name }}Configuring {{ authn_setup_prop }}"
  blockinfile:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_setup_prop }}"
    block: |
      {{ glassfish_cnf }}

#---

#---Properties---

- name: "{{ play_name }}Creating {{ authn_prop }}"
  file:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_prop }}"
    state: touch

#--TODO!--Move block to variable

- name: "{{ play_name }}Creating usernames and passwords in {{ authn_prop }}"
  blockinfile:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_prop }}"
    block: |
      #User list
      user.list = root ingest {{ user_name }}

      user.root.password = {{ mysql_root_pass }}
      user.ingest.password = ingest
      user.{{ user_name }}.password = {{ user_pass }}

      mechanism = simple

#---

#---Running Setup---

- name: "{{ play_name }}Installing Simple Authentication"
  shell:
    cmd: ./setup install
    chdir: "/home/{{ user_name }}/authn.simple"

