---

- name: "{{ play_name }}Starting {{ glassfish_domain }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ user_name }}/glassfish4/bin"
  command: "nohup {{ item }}"
  with_items:
  - "asadmin restart-domain {{ glassfish_domain }}"
  - "asadmin list-domains"

- name: "{{ play_name }}Checking download directory"
  file:
    path: "{{ download_dir }}"
    state: directory

- name: "{{ play_name }}Downloading {{ authn_zip }}"
  get_url:
    url: "{{ authn_src }}"
    dest: "{{ download_dir }}"

- name: "{{ play_name }}Unzipping {{ authn_zip }}"
  unarchive:
    src: "{{ download_dir }}{{ authn_zip }}"
    dest: "/home/{{ user_name }}"
    remote_src: yes

- name: "{{ play_name }}Creating {{ authn_setup_prop }}"
  file:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_setup_prop }}"
    state: touch

- name: "{{ play_name }}Configuring {{ authn_setup_prop }}"
  blockinfile:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_setup_prop }}"
    block: |
      {{ glassfish_cnf }}

- name: "{{ play_name }}Creating {{ authn_prop }}"
  file:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_prop }}"
    state: touch

- name: "{{ play_name }}Creating usernames and passwords in {{ authn_prop }}"
  blockinfile:
    path: "/home/{{ user_name }}/authn.simple/{{ authn_prop }}"
    block: |
      #User list
      user.list = root ingest {{ user_name }}

      user.root.password = {{ mysql_root_pass }}
      user.ingest.password = ingest
      user.{{ user_name }}.password = {{ user_pass }}

      mechanism = simple

- name: "{{ play_name }}Installing Simple Authentication"
  shell:
    cmd: ./setup install
    chdir: "/home/{{ user_name }}/authn.simple"

