---

- name: "{{ play_name }}Loading Pre-playbook Check"
  include: "preplay.yml"

#---

#---Downloading Storage plugin---

- stat:
    path: "{{ download_dir }}{{ storage_zip }}"
  register: sp_zip

- name: "{{ play_name }}Downloading '{{ storage_zip }}' to '{{ download_dir }}'"
  get_url:
    url: "{{ storage_src }}"
    dest: "{{ download_dir }}"
  when: sp_zip.stat.exists == false

#---

#---Unziping Storage Plugin---

- stat:
    path: "{{ storage_path }}"
  register: sp_dir

- name: "{{ play_name }}Unziping {{ storage_zip }}"
  unarchive:
    src: "{{ download_dir }}{{ storage_zip }}"
    dest: "{{ user_home }}/"
    remote_src: yes
  when: sp_dir.stat.exists == false

#---

#---Creating Directories---

- name: "{{ play_name }}Making directories to store data - '{{ dir_main }}' and '{{ dir_archive }}'"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dir_main }}"
    - "{{ dir_archive }}"

#---

#---Properties files---

- name: "{{ play_name }}Creating properties files in '/home/{{ user_name }}/ids.storage_file/'"
  file:
    path: "{{ storage_path }}/{{ item }}"
    state: touch
  with_items:
    - "{{ storage_main }}"
    - "{{ storage_archive }}"
    - "{{ storage_setup }}"
  
- name: "{{ play_name }}Configuring properties files - Adding storage directories"
  lineinfile:
    path: "{{ storage_path }}/{{ item.file }}"
    regexp: "dir="
    line: "{{ item.line }}"
  with_items:
    - { file: "{{ storage_main }}", line: "dir={{ dir_main }}" }
    - { file: "{{ storage_archive }}", line: "dir={{ dir_archive }}" }

- name: "{{ play_name }}Configuring {{ storage_setup }} - Adding Glassfish block"
  blockinfile:
    path: "{{ storage_path }}/{{ storage_setup }}"
    block: "{{ glassfish_cnf }}"

#---


#---Running Setup---

#NOTE
#This task needs work as it returns errors on the first run, however the setup is actually succesful.
#Currently it simply ignores errors, this is not ideal as any genuine errors will be ignored.

- name: "{{ play_name }}Installing IDS Storage"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ glassfish_path }}/bin"
  shell:
    cmd: ./setup install
    chdir: "{{ storage_path }}"
  ignore_errors: yes

#---
