---

- name: "{{ play_name }}Loading Pre-playbook Check"
  include: "preplay.yml"

#---

#---Downloading TopCat---

- stat:
    path: "{{ download_dir }}{{ topcat_zip }}"
  register: tc_zip

- name: "{{ play_name }}Downloading {{ topcat_zip }} to '{{ download_dir }}'"
  get_url:
    url: "{{ topcat_src }}"
    dest: "{{ download_dir }}"
  when: tc_zip.stat.exists == false

#---

#---Unzipping TopCat

- stat:
    path: "{{ topcat_path }}"
  register: tc_dir    

- name: "{{ play_name }}Unzipping {{ topcat_zip }}"
  unarchive:
    src: "{{ download_dir }}{{ topcat_zip }}"
    dest: "{{ user_home }}/"
    remote_src: yes
  when: tc_dir.stat.exists == false

#---

#---Setup Properties File

- name: "{{ play_name }}Creating {{ topcat_setup }}"
  file:
    path: "{{ topcat_path }}/{{ topcat_setup }}"
    state: touch

- name: "{{ play_name }}Configuring {{ topcat_setup }}"
  blockinfile:
    path: "{{ topcat_path }}/{{ topcat_setup }}"
    block: |
      {{ glassfish_cnf }}    
      {{ mysql_cnf }}
      {{ email_cnf }}

#---

#---Properties File---
      
- name: "{{ play_name }}Creating {{ topcat_prop }}"
  copy:
    src: "{{ topcat_path }}/{{ topcat_prop }}.example"
    dest: "{{ topcat_path }}/{{ topcat_prop }}"
    remote_src: yes
  
- name: "{{ play_name }}Configuring {{ topcat_prop }}"
  lineinfile:
    path: "{{ topcat_path }}/{{ topcat_prop }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "mail.enable",    line: "mail.enable = {{ mail_enable }}"}
    - { regexp: "ids.getstatus",  line: "ids.getStatus.max = 100" }
    - { regexp: "poll.delay",     line: "poll.delay = 600" }
    - { regexp: "poll.interval",  line: "poll.interval.wait = 600" }
    - { regexp: "adminUserNames", line: "adminUserNames = {{ topcat_admin }}" }

#---

#---Json File---

- name: "{{ play_name }}Creating {{ topcat_json }}, {{ topcat_lang }} and {{ topcat_css }}"
  copy:
    src: "{{ topcat_path }}/{{ item }}.example"
    dest: "{{ topcat_path }}/{{ item }}"
    remote_src: yes
  with_items:
    - "{{ topcat_json }}"
    - "{{ topcat_lang }}"
    - "{{ topcat_css }}"

- name: "{{ play_name }}Configuring {{ topcat_json }}"
  replace:
    path: "{{ topcat_path }}/{{ topcat_json }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.rep }}"
  with_items:
    - { regexp: "https", rep: "http" }
    - { regexp: "8181",  rep: "8080" }
    - { regexp: "localhost", rep: "{{ inventory_hostname }}" }
    - { regexp: 'your facility name[^"]*', rep: "LILS" }

#---

#---Running Setup---

- name: "{{ play_name }}Installing TopCat"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ glassfish_path }}/bin"
  shell:
    cmd: ./setup install
    chdir: "{{ topcat_path }}"

#---
